name: automol
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2020.11.8
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=67.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=0.17.0
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - paramiko=2.7.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pygments=2.7.2
  - pynacl=1.4.0
  - pyparsing=2.4.7
  - pysftp=0.2.9
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyzmq=19.0.2
  - rdkit=2020.09.1
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.1
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xlrd=1.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - alembic==1.4.1
    - astunparse==1.6.3
    - azure-core==1.9.0
    - azure-storage-blob==12.6.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - cryptography==3.2.1
    - databricks-cli==0.14.0
    - docker==4.3.1
    - entrypoints==0.3
    - flake8==3.8.4
    - flask==1.1.2
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - gorilla==0.3.0
    - grpcio==1.33.2
    - gunicorn==20.0.4
    - idna==2.10
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - keras-preprocessing==1.1.2
    - mako==1.1.3
    - markdown==3.3.3
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - mlflow==1.11.0
    - msrest==0.6.19
    - numpy==1.19.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.1.4
    - prometheus-client==0.8.0
    - prometheus-flask-exporter==0.18.1
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - python-editor==1.0.4
    - pytz==2020.4
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - smmap==3.0.4
    - sqlalchemy==1.3.13
    - sqlparse==0.4.1
    - tabulate==0.8.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - urllib3==1.25.11
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
