dataset_location: 'data/dsgdb9nsd.xyz'
dataset_class: 'QM9'
labels: ['homo']
models_filter: ['w', ['GaussianProcessRegressor', 'MLPRegressor', 'LinearRegression', 'GradientBoostingRegressor']]
problem: regression
amount: 10
