dataset_location: 'lsdf:///lsdf/kit/iti/projects/aimat/datasets/dsgdb9nsd'
dataset_class: 'QM9'
labels: ['homo']
models_filter: ['w', ['GaussianProcessRegressor', 'MLPRegressor', 'LinearRegression', 'GradientBoostingRegressor']]
problem: regression
amount: 10
