amount: 50
custom_features:
  feature123:
    file_link: https://raw.github.com/ff781/b/main/custom_function.py
    function_name: a
    requirments: ['smiles', 'coords']
    type: 'vector'
dataset_location: 'lsdf:///lsdf/kit/iti/projects/aimat/datasets/dsgdb9nsd'
dataset_class: 'QM9'
dataset_split:
  method: k_fold
  params: [10, 5]
labels: ['homo']
# w/b: whitelist/blacklist model_names
# type: custom, sklearn, tensorflow, keras, etc.
# model_names: probably need to switch this up for custom models
models_filter:
  - whitelist: 1
    git_uri: sklearn
    entry_point: train
    model_names: ['GaussianProcessRegressor', 'MLPRegressor', 'LinearRegression', 'GradientBoostingRegressor']
problem: regression
