dataset_location: 'data/dsgdb9nsd.xyz'
dataset_class: 'QM9'
labels: ['homo']
models_to_include: ['RandomForestRegressor']
#models_to_exclude: ['GaussianProcessRegressor', 'MLPRegressor', 'LinearRegression', 'GradientBoostingRegressor']
problem: regression
amount: 10
