dataset_location: 'lsdf:///lsdf/kit/iti/projects/aimat/datasets/dsgdb9nsd'
dataset_class: 'QM9'
custom_features:
  feature123:
    file_link: https://raw.github.com/ff781/b/main/custom_function.py
    function_name: a
    input: (smiles, coords)
    iam: [vector]
labels: ['homo']
models_filter: ['w', ['GaussianProcessRegressor', 'MLPRegressor', 'LinearRegression', 'GradientBoostingRegressor']]
problem: regression
amount: 10
